CREATE TABLE ZOO_AND_RESERVE(
ZOO_ID INT PRIMARY KEY NOT NULL,
ZOO_NAME VARCHAR(50) NOT NULL,
ZOO_LOCATION VARCHAR(50) NOT NULL
);

SELECT * FROM ZOO_AND_RESERVE;

DROP TABLE ZOO_AND_RESERVE;


CREATE TABLE WILDLIFE(
WILDLIFE_ID INT PRIMARY KEY,
ZOO_ID INT NOT NULL,
PERSONNEL_ID INT,
FEED_ID INT,
WILDLIFE_TYPE VARCHAR(50) NOT NULL,
WILDLIFE_NAME VARCHAR(150) NOT NULL,
WILDLIFE_SPECIES_NAME VARCHAR(100) NOT NULL,
WILDLIFE_HABITAT VARCHAR(300) NOT NULL,
WILDLIFE_DATE_OF_TRANSPORTATION DATE,
WILDLIFE_BEHAVIOUR VARCHAR(1000) NOT NULL,
FUN_FACT_ABOUT_WILDLIFE VARCHAR (500),
FOREIGN KEY (ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT,
FOREIGN KEY(FEED_ID) REFERENCES FEED(FEED_ID) ON DELETE RESTRICT
);

SELECT * FROM WILDLIFE;

DROP TABLE WILDLIFE;


CREATE TABLE PERSONNEL(
PERSONNEL_ID INT PRIMARY KEY,
ZOO_ID INT,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
GENDER VARCHAR(25),
ADDRESS VARCHAR(100),
BANK VARCHAR(100),
BANK_ACCOUNT_NUMBER INT,
POSITION_OF_PERSONNEL VARCHAR(100),
SALARY_IN_DOLLARS INT,
DATE_EMPLOYED DATE,
DEPARTURE_DATE DATE,
PERSONNEL_DUTIES VARCHAR(255),
FOREIGN KEY (ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT
);

SELECT * FROM PERSONNEL;

DROP TABLE PERSONNEL;


CREATE TABLE ZOO_AND_RESERVE_EQUIPMENT(
EQUIPMENT_ID INT PRIMARY KEY,
ZOO_ID INT,
PERSONNEL_ID INT,
EQUIPMENT_NAME VARCHAR(100),
EQUIPMENT_TYPE VARCHAR(255),
SERVICE_DATE DATE,
EQUIPMENT_AVAILABILITY BOOLEAN,
COST_OF_EQUIPMENT_REPAIR_IN_DOLLARS INT,
PURCHASE_DATE DATE,
EQUIPMENT_PRODUCTION_COMPANY VARCHAR(255),
EQUIPMENT_USE VARCHAR(255),
FOREIGN KEY (ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT
);

SELECT * FROM ZOO_AND_RESERVE_EQUIPMENT;

DROP TABLE ZOO_AND_RESERVE_EQUIPMENT;


CREATE TABLE FEED(
FEED_ID INT PRIMARY KEY,
ZOO_ID INT,
PERSONNEL_ID INT,
FEED_NAME VARCHAR(255),
PURCHASE_DATE DATE,
FEED_COST_IN_DOLLARS DATE,
EXPIRY_DATE_OF_FEED DATE,
FEED_PRODUCTION_COMPANY VARCHAR(255),
FOREIGN KEY(ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY (PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT
);

SELECT * FROM FEED;

DROP TABLE FEED;


CREATE TABLE MEDICINE(
MEDICINE_ID INT PRIMARY KEY,
ZOO_ID INT,
PERSONNEL_ID INT,
MEDICINE_NAME VARCHAR(255),
PURCHASE_DATE DATE,
MEDICINE_COST_IN_DOLLARS INT,
EXPIRY_DATE_OF_MEDICINE DATE,
MEDICINE_MANUFACTURER VARCHAR(255),
PHARMACY_OF_PURCHASE VARCHAR(255),
DISEASE_MEDICINE_WAS_BOUGHT_FOR VARCHAR (255),
WILDLIFE_MEDICINE_WAS_BOUGHT_FOR VARCHAR(255),
QUANTITY_OF_MEDICINE_BOUGHT VARCHAR(25),
FOREIGN KEY(ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT
);

SELECT * FROM MEDICINE;

DROP TABLE MEDICINE;


CREATE TABLE DISEASE(
DISEASE_ID INT PRIMARY KEY,
DISEASE_NAME VARCHAR(255),
WILDLIFE_ID INT, --WILDLIFE_ID Refers to the wildlife that have been affected by a specific disease--
WILDLIFE_CASUALTIES INT,
START_OF_DISEASE DATE,
END_OF_DISEASE DATE,
MEDICINE_ID INT,
ZOO_ID INT,
PERSONNEL_ID INT,
DISEASE_SYMPTOMS VARCHAR(255),
FOREIGN KEY(ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(MEDICINE_ID) REFERENCES MEDICINE(MEDICINE_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT,
FOREIGN KEY(WILDLIFE_ID) REFERENCES WILDLIFE(WILDLIFE_ID) ON DELETE RESTRICT
);

SELECT * FROM DISEASE;

DROP TABLE DISEASE;


CREATE TABLE ZOO_AND_RESERVE_INFRASTRUCTURE(
INFRASTRUCTURE_ID INT PRIMARY KEY,
ZOO_ID INT,
PERSONNEL_ID INT,
INFRASTRUCTURE_NAME VARCHAR(255),
INFRASTRUCTURE_USE VARCHAR(255),
INFRASTRUCTURE_COST_IN_DOLLARS INT,
DATE_BUILT DATE,
MAINTENANCE_COST_IN_DOLLARS INT,
FOREIGN KEY(ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT
);

SELECT * FROM ZOO_AND_RESERVE_INFRASTRUCTURE;

DROP TABLE ZOO_AND_RESERVE_INFRASTRUCTURE;


CREATE TABLE ACCOUNTS(
ACCOUNT_ID INT PRIMARY KEY,
ZOO_ID INT,
PERSONNEL_ID INT,
TOTAL_SALARIES_PAID_IN_DOLLARS INT,
TOTAL_FEED_COST_IN_DOLLARS INT,
TOTAL_EQUIPMENT_COST_IN_DOLLARS INT,
TOTAL_EQUIPMENT_MAINTENANCE_COST_IN_DOLLARS INT,
TOTAL_MEDICINE_COST_IN_DOLLARS INT,
TOTAL_INFRASTRUCTURE_COST_IN_DOLLARS INT,
TOTAL_WILDLIFE_MAINTENANCE_COST_IN_DOLLARS INT,
TOTAL_REVENUE_GENERATED_PER_MONTH INT,
FOREIGN KEY(ZOO_ID) REFERENCES ZOO_AND_RESERVE(ZOO_ID) ON DELETE RESTRICT,
FOREIGN KEY(PERSONNEL_ID) REFERENCES PERSONNEL(PERSONNEL_ID) ON DELETE RESTRICT
);

SELECT * FROM ACCOUNTS

DROP TABLE ACCOUNTS